# For more details, see https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
  workflow_call:
    inputs:
      UBUNTU_CODE:
        description: 'Ubuntu release code'
        default: '22.04'
        required: true
        type: string
      UBUNTU_CODE_NAME:
        description: 'Ubuntu release code name'
        default: 'jammy'
        required: true
        type: string
      PLATFORMS:
        description: 'Host platforms'
        default: 'linux/amd64'
        required: true
        type: string
      IMAGE_NAME:
        description: 'Docker image name'
        required: true
        type: string
      IMAGE_TAG:
        description: 'Docker image tag'
        required: true
        type: string
    secrets:
      DOCKER_HUB_USER_NAME:
        description: 'Docker hub user name'
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        description: 'Docker hub access token'
        required: true

# For more details, see https://github.com/docker/build-push-action
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-${{ inputs.UBUNTU_CODE }}
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ inputs.PLATFORMS }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER_NAME }}/${{ secrets.IMAGE_NAME }}:${{ inputs.UBUNTU_CODE }}-${{ secrets.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USER_NAME }}/${{ secrets.IMAGE_NAME }}:${{ inputs.UBUNTU_CODE }}-${{ secrets.IMAGE_TAG }}
          cache-to: type=inline
