# For more details, see https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
  workflow_call:
    inputs:
      ubuntu_code:
        description: 'Ubuntu release code'
        required: true
        type: string
      platforms:
        description: 'Host platforms'
        required: true
        type: string
      image_name:
        description: 'Docker image name'
        default: ${{ github.repository }}
        required: false
        type: string
      image_tag:
        description: 'Docker image tags'
        default: '0.0.1'
        required: false
        type: string
    secrets:
      DOCKER_HUB_USER_NAME:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true

# For more details, see https://github.com/docker/build-push-action
jobs:
  image:
    name: ${{ inputs.ubuntu_code }} / ${{ inputs.platforms }}
    runs-on: ubuntu-${{ inputs.ubuntu_code }}
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ inputs.image_name }}:${{ inputs.image_tag }}-${{ inputs.ubuntu_code }}
            ${{ inputs.image_name }}:latest
